import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './Navbar/Navbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
        <link rel="icon" type="image/svg+xml" href="https://i.ibb.co/grkxcB0/bookwarp.png" />
          <title>BookWarp</title>
        </head>
        <body className={inter.className}>
          <Navbar/>
          <main>
            {children}
          </main>
        </body>
    </html>
  )
}
